[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "specklegen-lg"
version = "v1.0"
description = "Code to generate speckle patterns."
authors = [
  { name = "thescepticalrabbit", email = "thescepticalrabbit@gmail.com" },
  { name = "pizzaman2629", email = "lavya2629@gmail.com"},
]
license = { file = "LICENSE" }
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: GNU LGPL",
    "Operating System :: OS Independent",
]
requires-python = ">=3.12"
dependencies = [
  "numpy<2.0.0",
  "scipy>=1.16.0",
  "commentjson>=0.9.0",
  "matplotlib<=3.8.2"
]

[tool.setuptools.packages.find]
where = ["src"]